"""
Django settings for BioPlot project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&+no^0$&78ie+=n#==k=%&zr(enoz9h#&+(3@jts-_pe4leqi&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]
X_FRAME_OPTIONS = 'SAMEORIGIN'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BioPlot',
]

ASGI_APPLICATION = 'BioPlot.routing.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BioPlot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BioPlot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
STATIC_URL = '/static/'

STATICFILES_DIRS = [(os.path.join(BASE_DIR, 'static'))]

# 全局变量
DIR_SCRIPT = f"{os.path.dirname(__file__)}/../bin"
DIR_TMP = os.path.abspath(f"{os.path.dirname(__file__)}/../Tmp/")

# RSCRIPT_BASE = "/dssg/home/sheny/anaconda3/envs/BioPlot_Base/bin/Rscript"
# RSCRIPT_KEGG = "/dssg/home/sheny/anaconda3/envs/BioPlot_kegg/bin/Rscript"
# RSCRIPT_ONCO = "/dssg/home/sheny/anaconda3/envs/BioPlot_oncoprint/bin/Rscript"
# RSCRIPT_SWIMMER = "/dssg/home/sheny/anaconda3/envs/BioPlot_swimmer/bin/Rscript"

RSCRIPT_BASE = f"{os.path.dirname(__file__)}/../conda_env/BioPlot/bin/Rscript"
RSCRIPT_KEGG = f"{os.path.dirname(__file__)}/../conda_env/kegg/bin/Rscript"
RSCRIPT_ONCO = f"{os.path.dirname(__file__)}/../conda_env/oncoprint/bin/Rscript"
RSCRIPT_SWIMMER = f"{os.path.dirname(__file__)}/../conda_env/swimmer/bin/Rscript"


DIR_DB = os.path.join(BASE_DIR, 'static', 'db')